### ISSUE TITLE
Error code 2168 0002

### ISSUE THREAD

**Issue by Zonemo001** [PoloNX/Ls-News#1]
Lorsque je clique sur Entrer à l'adresse, un problème survient
![Uploading 16814335918278925065876821391480.jpg…]()

**Comment by PoloNX** [comment]
Est ce que tu peux essayer de lancer l’homebrew launcher en lançant un jeu et en laissant appuyer le bouton r. De ce fait tu ne seras plus en applet mode

**Comment by PoloNX** [comment]
Je peux fermer l'issue ?
